### ISSUE TITLE
[Bug]: Display block not compatible with CSS layouts

### ISSUE THREAD

**Issue by nathancahill** [DaveKeehl/svelte-reveal#128]
### Describe the bug

This commit (https://github.com/DaveKeehl/svelte-reveal/commit/18d0f6d58e0e912602326394ca4a939a0e3bcb89) adds extra CSS properties to the element. This breaks other CSS layouts if `display` is set to `flex` or `grid` etc.

The correct way to do this to let the user set `display: block` on the element if needed.

### Reproduction

Any example shows the properties being applied.

### System Info

```shell
Latest version, all browsers.
```

### Severity

Serious, but I can work around it

### Additional Information

Happy to submit a PR with a fix.

**Comment by DaveKeehl** [comment]
Hi, thanks for reaching out. Feel free to submit a PR. I'll take a look at it ASAP

**Comment by DaveKeehl** [comment]
I just released version 0.6.0 which solves your problem. Thanks for the feedback and suggestions! I've also updated the REPL example.
