### ISSUE TITLE
[Bug]: Inline styles break Svelte Reveal

### ISSUE THREAD

**Issue by agamurian** [DaveKeehl/svelte-reveal#182]
### Describe the bug

Relation on styles.
inline styles break svelte-reveal

for example color: #ff000088 or color: #eee7 will just leave it transparent

#174 transiton in invisbly setted for element making it wierd on resize for example.

### Reproduction

<a use:reveal style="color: #4444; "></a>

### System Info

```Shell
ubuntu, firefox, sveltekit
```

### Severity

Annoyance

### Additional Information

my first bug report in life ever ))

**Comment by DaveKeehl** [comment]
Hi, thank you for reporting this issue. I'm aware of issues relating to styling that would need to be adressed. I currently don't have a lot of time to work on this project, but I'll see what I can do.

Do you have a reproduction environment?

**Comment by DaveKeehl** [comment]
@agamurian I've just tried to reproduce what you mentioned about inline styles, but I wasn't able to break Svelte Reveal. Do you still have a reproduction environment around that I could take a look at?

**Comment by DaveKeehl** [comment]
Sorry for the long wait. It should be fixed now! Please open a new issue if you notice other weird behaviors 🙏🏻
