### ISSUE TITLE
[Bug]: Demo error

### ISSUE THREAD

**Issue by Saad5400** [DaveKeehl/svelte-reveal#206]
### Describe the bug

Error, in the demo

### Reproduction

Open the demo

### System Info

```Shell
Not sure
```

### Severity

Critical

**Comment by Saad5400** [comment]
I got the same error after installing the package.

Seems like the folder is being installed empty without the src folder.

**Comment by DaveKeehl** [comment]
Yeah unfortunately I noticed that too! It's likely to be a misconfiguration of the release workflow, because it works fine on my machine. Will fix ASAP!

**Comment by DaveKeehl** [comment]
Patch 1.0.4 is out, fixing the broken published package! Sorry for the inconvenience
